### ISSUE TITLE
[gb57e13ff6] [Exhumed] Some menu sounds have gone quiet

### ISSUE THREAD

**Issue by sinisterseed** [coelckers/Raze#96] opened 2020-09-29 15:28 UTC
Namely, navigating the menus is silent now, all these sounds are gone, just the open menu sound still works.

**Comment by coelckers** [comment] 2020-09-29 22:38
No problems here. All these sounds play as expected.

**Comment by sinisterseed** [comment] 2020-09-30 10:28
Not for me, not anymore, in both self-compiled builds with 0.7.1's binaries and in DRD Team autobuilds.

Most curious. It actually got worse, going through the options is now quiet too.

**Comment by coelckers** [comment] 2020-09-30 11:30
Please check the "Sound in menus" option,. I can confirm that I hear all the sounds you list as missing.

**Comment by sinisterseed** [comment] 2020-09-30 12:09
Nope, nothing, and it's ON.

I only hear the mummy laughing and the open sound, after that, navigating the menus is silent.

**Comment by mjr4077au** [comment] 2020-10-02 21:47
I can't validate this one myself, I hear all sounds like Graf can.

**Comment by mjr4077au** [comment] 2020-10-05 05:31
Edited my comment above, been able to replicate this on a fresh config, but an older one is carrying over some setting perhaps. Investigating.

**Comment by mjr4077au** [comment] 2020-10-05 05:51
Broken from a9ca6c8081a158dc63a39848457245f68940512b onwards.

**Comment by coelckers** [comment] 2020-10-05 06:38
Oh shit, I think this might the cause of most of those weird Exhumed sound issues. It allocated a sound info struct without fully initializing it. And here it just so happened that the change in size caused undefined behavior in a field that really could silence the sound. That commit was fine, it just changed the memory layout to change how the bug manifested itself.

@sinisterseed Can you check this out if you find some time and also cross check the other sound bugs? A potential fix has been committed

**Comment by mjr4077au** [comment] 2020-10-05 06:49
This is dramatically better across the board and I'm hearing more sounds than I've heard thus far, but it's exacerbating some of those `>>>>>>>>>>>> Received AL error Invalid Value (0xa003), oalsound.cpp:955` issues.

**Comment by coelckers** [comment] 2020-10-05 06:52
I hope I can get them, too, so that I can investigate the reason. Good to hear that this seems to solve the problems. In hindsight it probably wasn't that bad that yesterday I did not manage to release 0.7.2. This sound fix is definitely worth a small delay. :)

**Comment by mjr4077au** [comment] 2020-10-05 06:56
Yeah, definitely is. I've seen comments about them persisting so finally getting them close to extinction is a great thing 😁.

**Closed** 2020-10-05 09:24 UTC
Labels: bug

**Comment by sinisterseed** [comment] 2020-10-05 09:40
I go missing for a day and I see this now eh?

Damn awesome if this has revealed a deeper issue and now more sounds have been fixed :) . Time to kick ass.

> Edited my comment above, been able to replicate this on a fresh config, but an older one is carrying over some setting perhaps. Investigating.

As I said, it was in both self-compiled builds and DRD Team ones, so it had to exist for real 😉 .

**Comment by coelckers** [comment] 2020-10-05 10:40
It was actually quite obvious that some uninitialized data was at fault here. That linked commit just gave me an opportunity to look for when these newly added variables get set and suddenly I had found the place where something was not right.
