### ISSUE TITLE
Blood - Lifeleech bugged

### ISSUE THREAD

**Issue by Axldomi** [coelckers/Raze#520] opened 2021-08-24 19:03 UTC
The lifeleech seems bugged. It does not seems to do damage anymore towards enemies. Or the enemies will just disappear when shot with the lifeleech.

**Comment by coelckers** [comment] 2021-08-25 06:51
fixed in c80831555ca34bd84e6ca13fa3412726589a1452

Caused by trying to gradually phase out one of Build's biggest fuckups and missing a small thing.

**Closed by coelckers** 2021-08-25 06:51 UTC
Labels: bug
