### ISSUE TITLE
[General]: Graphical corruption on Windows with latest NVIDIA drivers.

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#92] opened 2020-09-27 20:28 UTC
Lodging here from Discord. Below is what a user gets. He's using a GTX 1060 and I can corroborate this with the latest drivers on my GTX 970.

![image](https://user-images.githubusercontent.com/48643140/94374997-b9707380-0153-11eb-8afe-f8d32962efcc.png)

**Comment by coelckers** [comment] 2020-09-27 20:30
Oh my, NVidia has surely dropped the ball this time. Is this only for palette emulation mode or general?

**Comment by mjr4077au** [comment] 2020-09-27 20:33
I've seen it on both modes. Basically just shake the mouse around and the corruption goes away. It's only on the initial viewport of a fresh load.

**Comment by Phredreeke** [comment] 2020-09-27 20:33
Interesting. Someone in the BuildGDX Discord said they had similar issues with palette emulation in that port on latest NVidia drivers.

**Comment by coelckers** [comment] 2020-09-27 20:37
What does GZDoom say?
I am surely not installing such a broken driver.

**Comment by sinisterseed** [comment] 2020-09-27 20:42
I've been experiencing this for quite a while now, mentioned this before but I couldn't get Graf to reproduce it as well.

No idea if it's a driver issue, I've not had this nonsense happen in 0.6.0, not to this extent - I could sometimes notice this randomly when pausing the game in SW, but it was never this bad. Now it's somewhat of a common occurrence. It goes away by simply moving around, but it seems to trigger randomly. Sometimes I see it, sometimes I don't.

It's unrelated to palette emulation and other graphical setting I think, I can see it on various configurations.

I'm on driver version 446.16.

**Comment by mjr4077au** [comment] 2020-09-27 20:46
Sounds like this will be a wild goose chase. I won't be at home for ~36 hours but will test GZDoom out properly then and might go between a few driver releases to find out where the issues started. Perhaps then NVIDIA's release notes might give an indicaton.

**Comment by mjr4077au** [comment] 2020-09-27 20:47
FWIW, on Linux with NVIDIA's binary blob propietary driver, I wasn't able to replicate this.

**Comment by coelckers** [comment] 2020-09-27 20:48
I'm on 445.75, never had any problems with it.

**Comment by mjr4077au** [comment] 2020-09-27 20:51
~446 like sinisterseed has said is probably around the time it started. I'm into the 45x.xx versions now and it's no better.

**Comment by sinisterseed** [comment] 2020-09-27 20:54
This is gonna be a bitch to troubleshoot I think, as I said, it also seems to vary in intensity between our builds. In 0.6.0 I've never seen it so aggressive, so I wonder if it isn't a change we made somewhere that makes the render explode.

**Comment by coelckers** [comment] 2020-09-27 21:29
Yes, it's gonna be a bitch. I just tried the latest driver anyway, after making sure I have the old one for rolling back - and it works fine. I wouldn't be surprised if this is some Windows 10 fuckup by Microsoft.

**Comment by sinisterseed** [comment] 2020-09-27 21:33
Wouldn't be too sure about that. I would expect other GL based apps to exhibit similar issues unless it's something very specific, and Raze is the only one to exhibit this corruption.

**Comment by mjr4077au** [comment] 2020-09-27 21:37
I'm on Windows 10 Enterprise 2004 (thanks, work!). Not sure what build everyone else is on.

**Comment by coelckers** [comment] 2020-09-27 21:40
The corruption suggests to me that something's going wrong in postprocessing of the 3D scene, not normal rendering. However, not being able to reproduce it I'd need a higher resolution screenshot - this one's too small to make out any potential hints.

**Comment by sinisterseed** [comment] 2020-09-27 21:40
Version 1909, build 18363.1082. Haven't uodated to 2004 yet.

**Comment by sinisterseed** [comment] 2020-09-28 08:32
Here's SW, now in glorious 1080p corruption:

![ShadowWarrior_0000](https://user-images.githubusercontent.com/57503728/94409074-5516d980-017e-11eb-8b89-d9c19d8f9e7a.png)

**Comment by coelckers** [comment] 2020-09-28 08:52
That looks really - interesting, especially how the corruption aligns with the sword sprite.
And since the area below the sword is not corrupted it's a clear indicator that it's not happening in the scene renderer but the postprocessor or the rendering of the weapon sprite itself.

**Comment by sinisterseed** [comment] 2020-09-28 09:03
> That looks really - interesting, especially how the corruption aligns with the sword sprite.
> And since the area below the sword is not corrupted it's a clear indicator that it's not happening in the scene renderer but the postprocessor or the rendering of the weapon sprite itself.

The whole screen was actually corrupted, but the movement of the sword's draw animation erased a part from it, which is why that portion is clean but the bottom right corner still exhibits some corruption.

As I said, the movement of the player's view port erases it, but in the instances where the corruption is observed when starting a game, some random, tiny dots may also appear on the screen when the player stops moving, after playing for a bit, despite cleaning the initial corruption.

**Comment by coelckers** [comment] 2020-09-28 10:41
> The whole screen was actually corrupted, but the movement of the sword's draw animation erased a part of it, which is why that portion is clean but the bottom right corner still exhibits some corruption.
> 

That makes even less sense, unless it accessed some uninitialized backbuffer and doing 2D stuff clears that buffer.

**Comment by sinisterseed** [comment] 2020-09-28 13:09
It is what it is 😉 , I can only tell what you're seeing.

**Comment by coelckers** [comment] 2020-09-28 21:17
Do you by any chance have gl_ssao enabled?

**Comment by sinisterseed** [comment] 2020-09-28 21:37
Doubt it, I never touch AO since I know it doesn't work right currently.

Regardless, I'll check this in the morning, but if the default is off, it should be off.

**Comment by sinisterseed** [comment] 2020-09-30 19:48
The number of users experiencing this is slowly increasing, Jarolf of DW brought this up recently too: https://www.doomworld.com/forum/topic/111839-source-port-introducing-raze-thats-one-duked-up-space-marine/?do=findComment&comment=2195884

https://static.doomworld.com/monthly_2020_09/1097432821_03-FSCorr.png.3effb74296e87333e879ac9916b9f922.png

**Comment by coelckers** [comment] 2020-10-01 05:21
This looks more and more that some postprocessing buffer is not getting cleared before reuse. Unfortunately it only seems to happen on Windows 10 and not on Windows 8, so I cannot get it reproduced on my own setup.

**Comment by sinisterseed** [comment] 2020-10-01 07:29
It's all the more curious insofar as it didn't happen in 0.6 either, which makes me think it's a change we made somewhere that now no longer plays too well.

And also never happening in GZDoom.

**Comment by mjr4077au** [comment] 2020-10-01 07:52
I'll be doing a significant amount of backtracing for #98 tonight to see whether we've ever had this working with the rebase so if I notice a demarcation point I'll be sure to advise.

**Comment by sinisterseed** [comment] 2020-10-01 08:03
Any ideas where to start? Because if we take that route, this is going to be a real bitch to troubleshoot.

We essentially have to go back some three months, and even there, who knows where to start looking.

**Comment by mjr4077au** [comment] 2020-10-01 08:21
For #98 I'll be going back to the first usable commits and will see what the go is. If it works fine, I'll go half way between then and now. If it works from there, go half forward again otherwise half back and just keep working it until I get to the issue.

For something like this issue, I don't recall it happening before the main loop cutover so I'd probably be starting there.

**Comment by sinisterseed** [comment] 2020-10-01 09:41
Yeah, same here, after the main loop transition it became rather frequent.

Some level of corruption existed even before though, but never in such intensity, which makes me think the main loop just made a core issue more noticeable rather than introducing it.

**Comment by mjr4077au** [comment] 2020-10-02 21:58
> Some level of corruption existed even before though, but never in such intensity, which makes me think the main loop just made a core issue more noticeable rather than introducing it.

Agreed. During some testing, I couldn't get these issues to happen on the old main loop, however I can't reliably make it happen on demand to 100% conclusively validate that something is wrong there. Happens on fresh or old configs, happens when I'm not trying to make it happen and never when I am.

I've already mentioned it but it also doesn't happen under Linux using NVIDIA's 455.23.04 driver which aside from the OS interface should be near 1:1 with the Windows NVIDIA driver.

I'm wondering whether it's some Windows Update issue that's caused the problem perhaps? I get we're on different versions (1909 vs. 2004 like I am) however they're both still within their support period by Microsoft and both get updates. I still need to try an older NVIDIA driver and see if that helps.

> Unfortunately it only seems to happen on Windows 10 and not on Windows 8, so I cannot get it reproduced on my own setup.

Windows 8? C'mon bruv! :laughing:. Genuinely like it or CBF'd to reformat?

**Comment by coelckers** [comment] 2020-10-02 22:01
Hey, I bought a good system in 2012, it's still working well enough so I have no need to pay $$$ for Windows 10.  This is running on a MSDN version from my former employer which I cannot upgrade.

**Comment by sinisterseed** [comment] 2020-10-05 13:40
> Hey, I bought a good system in 2012, it's still working well enough so I have no need to pay $$$ for Windows 10. This is running on a MSDN version from my former employer which I cannot upgrade.

You know you didn't have to, and actually still don't, if you know-how, right 😉 . Between W10 from version 1909 onwards and 8/8.1 I would never go back honestly.

BTW more goodness:

![ShadowWarrior_0000](https://user-images.githubusercontent.com/57503728/95086678-743adb80-0729-11eb-87e5-c56d42313604.png)

**Comment by coelckers** [comment] 2020-10-05 13:43
> You know you didn't have to, and actually still don't, if you know-how, right 😉 . Between W10 from version 1909 onwards and 8/8.1 I would never go back honestly. 10 is just so much better and a lot of the hatred it received is totally unwarranted.
> 

To make it abundantly clear: I won't install a pirated Windows version on my system. I am working in a company with close ties to Microsoft and I use the computer for professsional work, so I think you can do the math what might happen if it ever came out if I used something not 100% kosher.

**Comment by sinisterseed** [comment] 2020-10-05 13:45
> > You know you didn't have to, and actually still don't, if you know-how, right 😉 . Between W10 from version 1909 onwards and 8/8.1 I would never go back honestly. 10 is just so much better and a lot of the hatred it received is totally unwarranted.
> 
> To make it abundantly clear: I won't install a pirated Windows version on my system. I am working in a company with close ties to Microsoft and I use the computer for professsional work, so I think you can do the math what might happen if it ever came out if I used something not 100% kosher.

And what makes you think I was suggesting that? I said there's still a way to get it free, and I meant just that when I said it, it had no piracy undertones.

You're reading into something that does not exist.

**Comment by coelckers** [comment] 2020-10-05 13:56
No, I cannot get a free upgrade. My Windows comes from an old, expired MSDN account and any upgrade is blocked.

**Comment by sinisterseed** [comment] 2020-10-05 14:02
Well that's a shame then.

**Comment by markanini** [comment] 2020-10-08 06:42
Does it go away when disabling Anisotropic filtering in Nvidia control panel?

**Comment by coelckers** [comment] 2020-10-08 06:47
What prompted you to make that suggestion? Personal experience or do you have a link for an explanation?

**Comment by markanini** [comment] 2020-10-08 06:51
Because BuildGDX users are experiencing a similar corruption that's solved that way, according to Discord. No promises, I don't own a Nvidia GPU so I cant test it out.

**Comment by coelckers** [comment] 2020-10-08 06:53
That's really interesting. The renderers are totally different so it's a bit puzzling that both engines are showing problems with recent NVidia drivers.

Too bad that Vulkan currently does not work. It'd be an interesting case to test otherwise.

**Comment by sinisterseed** [comment] 2020-10-08 07:05
> Because BuildGDX users are experiencing a similar corruption that's solved that way, according to Discord. No promises, I don't own a Nvidia GPU so I cant test it out.

Most curious, I've never experienced any corruption in GDX.

**Comment by markanini** [comment] 2020-10-09 04:44
Here's what it look like in GDX: https://i.imgur.com/dyzwWXT.png

**Comment by coelckers** [comment] 2020-10-09 06:25
That's interesting. I witnessed a similar corruption like can be seen on the weapon and HUD once when drawing a palette emulated 2D sprite but wrote it off as a shader bug that needs to be investigated.
So, does the corruption here and in GDX only happen in palette emulated mode or also in true color mode? 
The one on the 2D elements looks like a texture sampling error for sure and all Raze screenshots only have corruption on the 3D scene but not the 2D elements that are drawn in true color.

**Comment by markanini** [comment] 2020-10-09 06:29
> So, does the corruption here and in GDX only happen in palette emulated mode or also in true color mode?
Only in palette emulated mode.

**Comment by coelckers** [comment] 2020-10-09 07:16
NVidia declaring war on retro gamers...? 👿

**Comment by sinisterseed** [comment] 2020-10-09 07:21
Not palette emulation specific for us. I saw it well before PE became functional again.

Mark did mention anisotropic filtering too. I wonder if that plays some role in this.

**Comment by mjr4077au** [comment] 2020-10-09 07:24
Same as sinisterseed, happens on either for me. Still perplexed by it not happening on Linux with the NVIDIA driver as well.

**Comment by sinisterseed** [comment] 2020-10-09 07:29
And apparently not on 8.1 either.

This is starting to make me wonder whether something changed in 10 behind the scenes, but I can't even begin to guess what. I don't recall any major update bringing changes to the APIs.

**Comment by coelckers** [comment] 2020-10-09 07:39
I got the same effect as on the 2D elements in the GDX screenshot on 8.1 as well.
It also makes sense that anisotropic filtering may make a difference.
With the new info I can day that this thing is most definitely a sampling error from the palette textures. It at least gives some hints at where to look for a solution. Since EDuke32 does not appear to be affected - at least it was never mentioned - it may give some hints.

**Comment by sinisterseed** [comment] 2020-10-09 11:31
And also, the corruption is truly on the entire screen for us when it happens.

Last time I had it in SW I figured I would scroll through the HUDs, and the more you know, after I cleaned the corruption on my screen and switched to the no HUD display mode, there was corruption behind the status bar too, which I had to clean manually.

**Comment by coelckers** [comment] 2020-10-09 11:34
The operative term being "behind".

**Comment by sinisterseed** [comment] 2020-10-09 11:34
Yes.

**Comment by sinisterseed** [comment] 2020-10-09 18:50
> Mark did mention anisotropic filtering too. I wonder if that plays some role in this.

I think we found the culprit.

I've been testing other things which involved lots of game restarts and whitching between games, and I decided to turn **Anisotropic Filtering** off to see what happens. After a considerably amount of time and continuous switching between games, I have to say I have not experienced the corruption again.

I think it happens with the PE as well despite it being physically unable to use the feature because the engine initializes it at startup anyway, then turns off because it says "no". **Texture filtering** seems to play no role in this whatsoever.

Huh, good job @markanini , you have found it 👍 .

**Comment by sinisterseed** [comment] 2020-10-09 18:56
Nah, spoke to soon it seems...

It manifested again eventually...

**Comment by coelckers** [comment] 2020-10-10 17:50
I just started up BloodGDX to check something out and got similar effects all over in palette emulation mode - all at the borders of individual texels. Changing anisotropic filtering does not change anything there - but the latest Raze works fine.
This is actually the same effect I once saw on the weapon which made me disable palette emulation there.
This is really weird.

**Comment by AnotherLife** [comment] 2020-10-14 12:43
It doesn't have anything to do with Win 10 because it happened to me when I downloaded Raze and tried Blood a couple of days ago. On fully updated Win 8.1. Nvidia driver version ... not sure, probably a few months behind, not at my PC now.

The screen steadily gets cleared up as the viewport changes and the correct colored pixels get drawn over the weirdness, lol :D

**Comment by sinisterseed** [comment] 2020-11-21 00:21
Another victim 😩 : https://www.doomworld.com/forum/topic/118220-powerslave-the-fps-now-available-on-gog/?do=findComment&comment=2220982

"Yes﻿﻿, it looked like that. This comment is accurate: 'It's only on the initial viewport of a fresh load.' And yes, Windows 10. I do indeed have﻿ an NVIDIA card, a 1650 ﻿Super.﻿"

**Comment by coelckers** [comment] 2020-11-21 08:11
Still no idea. I can reproduce the bugged palette emulation in BuildGDX, but never saw this effect in Raze. And not being able to see it in motion means I do not have any idea what might be causing it.

**Comment by sinisterseed** [comment] 2020-11-21 09:03
Still no luck with a W10 machine, I take it?

Seems to be most common there.

**Comment by coelckers** [comment] 2020-11-21 09:18
Make that "W10 machine with NVidia graphics". I have access to two laptops, one has AMD graphics and the other Intel only. And obviously on both the corruption does not happen.

**Comment by sinisterseed** [comment] 2020-11-21 09:22
Mighty convenient then, how it's so oddly specific to NVIDIA.

**Comment by coelckers** [comment] 2020-11-21 09:49
It's a driver bug - but since it only appears to happen with software that's not commercially relevant there's no pressure fixing it.

**Comment by sinisterseed** [comment] 2020-11-21 10:04
Are you sure? It may be relevant to file a bug report if that is indeed the case.

**Comment by coelckers** [comment] 2020-11-21 10:28
If it isn't hardware specific there must be a difference in the driver. Of course, being unable to reproduce it I can only guess.

**Comment by sinisterseed** [comment] 2020-11-21 11:23
Puzzling, trying to find where the bug is located will be like roulette then.

Well, all good fun at least - until it turns Russian 😉 .

**Comment by mjr4077au** [comment] 2020-12-29 06:11
Just advising that this still occurs as of Windows 10 20H2 and NVIDIA 460.89 drivers. Still working like a champion under Linux as well.

**Comment by markanini** [comment] 2020-12-29 12:51
The beginning or this youtubers playthrough in GDX showed some steps he made to get palette emulation to work: https://www.youtube.com/watch?v=KKluaKMCtq4 Needs the be redone each time a map loads.
Hope it can help this project.

**Comment by coelckers** [comment] 2021-03-22 22:14
Fixed with a12f2778460ccc17a55e3eff1d8f8a2a66e7f140

**Closed by coelckers** 2021-03-22 22:14 UTC
Labels: bug, help wanted
