### ISSUE TITLE
[BUG] [Exhumed/SW/Blood] Issue with overlapping sectors

### ISSUE THREAD

**Issue by mjr4077au** [coelckers/Raze#580] opened 2021-11-06 11:09 UTC
### Raze version

1.2.1

### Which game are you running with Raze?

Exhumed/Powerslave

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Portal glitch that can be seen here at about ~9-10 seconds in. Very brief. https://youtu.be/xxzyVB2ByA4

**Comment by sinisterseed** [comment] 2021-11-07 15:29
I noticed this ages ago, now that I took a closer look.

I'm suspecting this and Lunatic Fringe, plus the top of the library on CP03 when going up the stairs sometimes all share a common root cause, as the symptoms are the same under similar circumstances. There's a larger portal in all of those areas which causes a brief flicker.

**Comment by coelckers** [comment] 2021-11-09 18:50
Exhumed does not have portals. And neither does Lunatic Fringe. What both maps do feature is overlapping sector parts, and the updatesector code has been heavily modifeid for EDuke32. BTW I haven't managed to get such effects on any of these maps recently.

**Comment by mjr4077au** [comment] 2021-11-09 21:49
> Exhumed does not have portals. And neither does Lunatic Fringe. What both maps do feature is overlapping sector parts, and the updatesector code has been heavily modifeid for EDuke32. BTW I haven't managed to get such effects on any of these maps recently.

That's my bad with using the incorrect terminology. I can reliably reproduce these at a moment's notice, I think they're always going to be hard to reproduce as long as you're on a 60Hz display. I can't express how substantial the difference of 144Hz is, the notion that human eyes can only pick up 60 fps is definitely false.

**Comment by sinisterseed** [comment] 2021-11-10 09:08
Yeah, my bad too, oops. Brain fart moment for me.

Either way, the point stands, I'll see if I can still reproduce them myself too, but I doubt they're render specific, it happened in both last time, and that probably hasn't changed since.

**Comment by sinisterseed** [comment] 2021-11-10 20:27
> I'll see if I can still reproduce them myself too

Yeap, definitely still a thing, still randomly thrashing the view.

**Comment by coelckers** [comment] 2021-11-28 20:30
I still haven't managed to reproduce it so any attempt to add debugging aids to updatesector revealed nothing at all.

**Comment by mjr4077au** [comment] 2021-11-28 21:29
You can get it just by circle strafing around that entire area around the pool, it doesn't have to be that particular spot. Maybe slowed down time would help. When I have time I'll do that myself and see if its possible to actually have the character stop on an overlapping point so I can save it there.

**Comment by coelckers** [comment] 2021-11-29 23:15
fixed in 64cad55d73e4752c1c428f8821a2ef0ec62d6e63

**Closed by coelckers** 2021-11-29 23:15 UTC
Labels: bug, on hold
