### ISSUE TITLE
[BUG] Bath House crashes on Launch of Map

### ISSUE THREAD

**Issue by hegyak** [coelckers/Raze#598] opened 2021-12-12 02:54 UTC
### Raze version

1.3.0

### Which game are you running with Raze?

Shadow Warrior

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Attempting to enter/load Bath House causes the game to crash and generate an error report.

If you need more information, or a save before the end of the Sumo Boss, can provide that as well.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Beat the Sumo Boss and go past the results screen
2. Client Crashes and generates a Dump Report

I am using Shadow Warrior 1.2 GRP from GoG.

### Provide a Log

[CrashReport.zip](https://github.com/coelckers/Raze/files/7698035/CrashReport.zip)
Crash report the Client Generated.

**Comment by mjr4077au** [comment] 2021-12-12 03:28
Thanks for the report. The report here is a duplicate of this one in the ZDoom forums we were by chance talking about today. https://forum.zdoom.org/viewtopic.php?f=340&t=73002

This bug will be addressed before a 1.3.1 release comes out. Thank you for reporting the issue and sorry it went unnoticed. In the mean time, perhaps just turn palette emulation off for now, or at least until the level is loaded. 1.3.1 should contain a true fix though.

Screenshot of backtrace + save on 1.3.0 just before the crash occurs below for posterity. These are also on the ZDoom forum post.

![image](https://user-images.githubusercontent.com/48643140/145699033-0c624075-c95a-4198-989d-91aa6263c8e1.png)

[save0003.zip](https://github.com/coelckers/Raze/files/7698063/save0003.zip)

**Comment by coelckers** [comment] 2021-12-12 08:43
fixed in c2f29b8849d4eb30a65008ba1c208cad909310e9

**Closed by coelckers** 2021-12-12 08:43 UTC
Labels: bug
