### ISSUE TITLE
[BUG] Some voxels face the wrong way

### ISSUE THREAD

**Issue by Talon1024** [coelckers/Raze#549] opened 2021-09-13 22:25 UTC
### Raze version

Git

### What Operating System are you using?

Linux x86_64

### Which game are you running with Raze?

Blood

### Relevant hardware info

Intel i5-4690K CPU, NVidia GeForce GTX 970 GPU

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

If you load the [Blood voxel pack](https://www.moddb.com/mods/blood-voxel-pack), some voxels face the wrong direction.

Commit 38b191a9532655786ce15bc5e6a1a482d943fdec

Screenshots:
![Blood_0017](https://user-images.githubusercontent.com/6550500/133164384-80cb4fe7-9754-4b2e-a25c-a77d5909e09d.png)
![Blood_0018](https://user-images.githubusercontent.com/6550500/133164387-d2d3cebb-a2e0-4fd9-8698-5d9d99052de0.png)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load Blood with the voxel pack addon from above
2. Start a new game on episode 3 "Farewell to Arms"
3. Beat the first level or warp to E3M2
4. Enter the Feinman Meats building from the front entrance
5. The light switch will not be aligned to the wall - instead, it will be half-inside the wall and half-outside the wall.
6. The "No Admittance" sign will look like a +

### Your configuration

```ini
testnewrenderer=true
```

**Comment by mjr4077au** [comment] 2021-10-20 09:07
@Talon1024 I can't replicate this, not at least on the current master. Can you please test again? I've tried both renderers.

**Comment by mjr4077au** [comment] 2021-10-21 06:07
This is a fresh game against master, with the voxel pack loaded. I simply can't trigger it.

![image](https://user-images.githubusercontent.com/48643140/138220875-91bf2e0c-fa1e-4458-88f1-04767399a3a9.png)

**Comment by Talon1024** [comment] 2021-10-21 10:50
It may be a Linux-specific bug then.

**Comment by coelckers** [comment] 2021-11-28 16:16
Doesn't happen for me. You got to check how it comes that the engine doesn't find the map hack on your system.

**Comment by mjr4077au** [comment] 2021-12-16 08:07
I'm going to close this one off for now. I've just tried a level transition from E3M1 to E3M2 without directly warping to the map and still cannot reproduce this. Screenshots below show the console with map transition and voxels on/off.

![Blood_0035](https://user-images.githubusercontent.com/48643140/146332236-3eee37e1-9066-42f3-ac77-1e7792973801.png)

![Blood_0036](https://user-images.githubusercontent.com/48643140/146332261-1bf7846d-687e-408b-a810-16b209bf7e18.png)

**Closed by mjr4077au** 2021-12-16 08:07 UTC
Labels: bug, question
