### ISSUE TITLE
[HELP] Can you please distribute a .deb package for Ubuntu LTS ?

### ISSUE THREAD

**Issue by xcom169** [coelckers/Raze#480] opened 2021-07-17 11:22 UTC
Hello All!

Can you please distribute a binary .deb package for Ubuntu 20.04 LTS ?

Thanks

**Comment by coelckers** [comment] 2021-07-17 19:33
Yes, we should. I actually have no idea why there is one for Raze while GZDoom routinely gets them. They are handled by somebody else so that person would have to answer.

**Comment by xcom169** [comment] 2021-07-18 06:31
I tried to compile it myself with cmake, but the final binary can't handle
the games correctly. I'm not sure why.

**Comment by alexey-lysiuk** [comment] 2021-07-18 06:47
Most likely, a pre-built binary will behave identically to yours. Where did you put games data? Please post entire directory tree with files of that location.

**Comment by xcom169** [comment] 2021-07-19 18:06
I used 
"
mkdir build
cd build
cmake  -DCMAKE_BUILD_TYPE=Release  ..
make
sudo make install
"
but there are multiple issues. 
I version number is not correct in the binary.
/usr/local/bin/raze can't find games.   If I run ./raze in tbe build dir. it works fine.

**Comment by alexey-lysiuk** [comment] 2021-07-19 19:02
You’re trying to answer questions nobody asked. Help us help you.

> but there are multiple issues.

This tells us nothing. What are those issues?

> I version number is not correct in the binary.

I guess, you downloaded source code from GitHub web page. To have correct version number you need clone repository with Git.

> /usr/local/bin/raze can't find games. If I run ./raze in tbe build dir. it works fine.

Once again, where did you put games data?

**Comment by xcom169** [comment] 2021-07-20 13:33
Here you are. Both of the problems. 

![image](https://user-images.githubusercontent.com/17802090/126332982-b0ab5af0-0a2a-49aa-9090-a86f00db1d91.png)
![image](https://user-images.githubusercontent.com/17802090/126333034-89386483-3010-43c9-b6dc-bbae8843b336.png)

**Comment by mjr4077au** [comment] 2021-07-27 01:03
Closing as it's a duplicate of #160. On the weekend, I'll see about doing a deb build for 1.1.3 though I've never packaged anything under Ubuntu.

**Closed by mjr4077au** 2021-07-27 01:03 UTC
Labels: question

**Comment by billbeans** [comment] 2024-12-27 14:35
Is this still happening? I can't make a functional build on Debian 12, and I see the topic was renamed as recently as May

**Comment by madame-rachelle** [comment] 2024-12-27 14:43
The person mainly responsible for the .deb packages for GZDoom is @Blzut3 - but he is doing it out of kindness and grace and I am not sure if he can be convinced to do it for Raze as well, but he's probably the best person to talk to in order to see if it will happen. GZDoom also has Flatpak packages maintained by @Eonfge but the same thing applies - he's also doing it out of kindness and so you'd have to convince him to be on board too.

One mitigating factor that could affect both of their decisions is Raze's messy licensing scheme. Since some of the code is protected by the Build license and not the GPL, the project is not technically 100% OSI compatible. This can easily cause problems with contributors deciding whether or not to advance the project with their own contributions, binary maintainers included.

**Comment by Eonfge** [comment] 2024-12-27 16:46
@madame-rachelle Thanks for your kind words. I try to help where I can, keeping Classic Doom alive and kicking.

Luckily, there is already a Raze package on Flathub:

https://flathub.org/apps/org.zdoom.Raze

I have no direct involvement with it, although we do occasionally share information about building and packaging.

> One mitigating factor that could affect both of their decisions is Raze's messy licensing scheme. Since some of the code is protected by the Build license and not the GPL, the project is not technically 100% OSI compatible.

No objections from me. I'm no purist, although I know that some contributors at Flathub are a little more rigid.

**Comment by Blzut3** [comment] 2024-12-28 00:21
The reason I haven't built deb packages for Raze is because I'm trying to phase out building packages by hand.  GZDoom is grandfathered in, but part of the CMake rewrite I did awhile ago to GZDoom was in preparation for switching to CPack which would enable me to package Raze once replicated here.  Unfortunately due to lack of proper communication/feedback that effort stalled for too long.  I need to find time to sit down again and redo that refactor and hopefully it's doesn't end up a repeat of last time.

**Comment by billbeans** [comment] 2025-01-02 23:26
Well, my self-compiled Raze binary randomly started working not long after I commented here. I don't know what I did, but at least I can play on Debian now.

It would still be nice to have a deb package. The Debian game-data-packager team seems to want it, or maybe they're already working on it. If you generate a data package for Redneck Rampage the install prompt actually recommends Raze, but there's no Raze in any Debian repos.
