### ISSUE TITLE
[BUG] Pressing Esc a few time during the startup sequence makes the game hang at title/splash screen

### ISSUE THREAD

**Issue by AtifArshad1995** [coelckers/Raze#632] opened 2022-01-22 20:38 UTC
### Raze version

1.3.1

### What Operating System are you using?

Windows 10

### Relevant hardware info

CPU = Intel i5-8250U, GPU = AMD Radeon 530, RAM = 4 GB

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Pressing Esc a few time during the startup sequence makes the game hang at title/splash screen. This can be reproduced consistently. I am using the 1.3.1 release.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Select any game (either Duke, Blood or SW should do it) and launch it
2. During the launching (when the loading bar is progressing), pressing Esc a few times
3. Now when the game will launch, it will hang at startup splash screen.

**Comment by coelckers** [comment] 2022-01-23 08:23
Duplicate of #174

**Closed by coelckers** 2022-01-23 08:23 UTC
Labels: bug
