### ISSUE TITLE
[Blood] E1M4 music starts playing after loading a save in E1M5.

### ISSUE THREAD

**Issue by valter12437** [coelckers/Raze#334] opened 2021-04-29 00:34 UTC
It happens with normal/quick saves & loads. The problem does not occur when loading an autosave however. Only tested with MIDI soundtrack.

**Comment by coelckers** [comment] 2021-05-01 19:07
What Raze version did you use? This should have been fixed long ago and I certainly cannot reproduce it.

**Comment by sinisterseed** [comment] 2021-05-01 19:10
Same here, hence no label currently.

Old Raze versions did have some random issues with music playback, but they should have all been ironed out.

**Comment by valter12437** [comment] 2021-05-01 21:08
It's version 1.0.3. Weirdly enough I'm unable to reproduce it again. But I will send my Save File, does that help in any way? The save was created in 1.0.3 as well.
[Save Game.zip](https://github.com/coelckers/Raze/files/6410299/Save.Game.zip)

**Comment by mjr4077au** [comment] 2021-07-20 09:00
I'm going to close this down, 1.0.3 was ages ago and no one can reproduce.

@valter12437 if it does happen again, please re-open the case and we'll try to work out what's happened.

**Closed** 2021-07-20 09:07 UTC
Labels: bug
